project_to_category = {
    # Big Data & Analytics
    'Hadoop Common': 'Big Data & Analytics', 'Hadoop Map/Reduce': 'Big Data & Analytics',
    'Hadoop HDFS': 'Big Data & Analytics', 'Hive': 'Big Data & Analytics',
    'Pig': 'Big Data & Analytics', 'Mahout': 'Big Data & Analytics',
    'Nutch': 'Big Data & Analytics', 'Solr': 'Big Data & Analytics',
    'Lucene - Core': 'Big Data & Analytics', 'Lucene.Net': 'Big Data & Analytics',
    'Drill': 'Big Data & Analytics', 'Spark': 'Big Data & Analytics',
    'Flink': 'Big Data & Analytics', 'Samza': 'Big Data & Analytics',
    'Storm': 'Big Data & Analytics', 'Kafka': 'Big Data & Analytics',
    'Oozie': 'Big Data & Analytics', 'Accumulo': 'Big Data & Analytics',
    'HBase': 'Big Data & Analytics', 'Apache Cassandra': 'Big Data & Analytics',
    'Phoenix': 'Big Data & Analytics', 'Giraph (Retired)': 'Big Data & Analytics',
    'Chukwa (retired)': 'Big Data & Analytics', 'Hama': 'Big Data & Analytics',
    'Ambari': 'Big Data & Analytics', 'Bigtop': 'Big Data & Analytics',
    'Sqoop (Retired)': 'Big Data & Analytics', 'Flume': 'Big Data & Analytics',
    'HCatalog': 'Big Data & Analytics', 'MRUnit': 'Big Data & Analytics',
    'Bookkeeper': 'Big Data & Analytics', 'ZooKeeper': 'Big Data & Analytics',
    'Tajo (Retired)': 'Big Data & Analytics', 'Tez': 'Big Data & Analytics',
    'Knox': 'Big Data & Analytics', 'MRQL': 'Big Data & Analytics',
    'Falcon': 'Big Data & Analytics', 'Sentry (Retired)': 'Big Data & Analytics',
    'Aurora': 'Big Data & Analytics', 'Slider': 'Big Data & Analytics',
    'Parquet': 'Big Data & Analytics', 'Calcite': 'Big Data & Analytics',
    'Kylin': 'Big Data & Analytics', 'SAMOA': 'Big Data & Analytics',
    'Zeppelin': 'Big Data & Analytics', 'Apache AsterixDB': 'Big Data & Analytics',
    'TinkerPop': 'Big Data & Analytics', 'Singa': 'Big Data & Analytics',
    'ORC': 'Big Data & Analytics', 'Atlas': 'Big Data & Analytics',
    'Myriad': 'Big Data & Analytics', 'Apache Trafodion (Retired)': 'Big Data & Analytics',
    'Apache Apex Core': 'Big Data & Analytics', 'Apache Apex Malhar': 'Big Data & Analytics',
    'Apache HAWQ (Retired)': 'Big Data & Analytics', 'Apache Horn': 'Big Data & Analytics',
    'Apache MADlib': 'Big Data & Analytics', 'Rya': 'Big Data & Analytics',
    'Metron (Retired)': 'Big Data & Analytics', 'SystemDS': 'Big Data & Analytics',
    'Kudu': 'Big Data & Analytics', 'TOREE': 'Big Data & Analytics',
    'Apache Arrow': 'Big Data & Analytics', 'Beam': 'Big Data & Analytics',
    'Edgent': 'Big Data & Analytics', 'Mnemonic': 'Big Data & Analytics',
    'Apache Gearpump': 'Big Data & Analytics', 'Apache Quickstep': 'Big Data & Analytics',
    'CarbonData': 'Big Data & Analytics', 'PIRK': 'Big Data & Analytics',
    'PredictionIO (Retired)': 'Big Data & Analytics', 'DistributedLog': 'Big Data & Analytics',
    'Livy': 'Big Data & Analytics', 'Apache Science Data Analytics Platform': 'Big Data & Analytics',
    'Apache MXNet (Retired)': 'Big Data & Analytics', 'Apache Crail': 'Big Data & Analytics',
    'Apache Pinot': 'Big Data & Analytics', 'Apache Marvin (Retired)': 'Big Data & Analytics',
    'Apache IoTDB': 'Big Data & Analytics', 'Apache Hudi': 'Big Data & Analytics',
    'Apache Submarine': 'Big Data & Analytics', 'Apache Datasketches': 'Big Data & Analytics',
    'StreamPipes': 'Big Data & Analytics', 'Apache InLong': 'Big Data & Analytics',
    'Apache YuniKorn': 'Big Data & Analytics', 'Apache Cloudberry': 'Big Data & Analytics',
    'Apache Cassandra Java driver': 'Big Data & Analytics', 'Apache Cassandra Go driver': 'Big Data & Analytics',
    'Apache Cassandra Analytics': 'Big Data & Analytics', 'Apache Gluten (incubating)': 'Big Data & Analytics',


    # Databases & Persistence
    'Derby': 'Databases & Persistence', 'iBatis for Java [READ ONLY]': 'Databases & Persistence',
    'iBatis for .NET': 'Databases & Persistence', 'JDO': 'Databases & Persistence',
    'OJB': 'Databases & Persistence', 'Torque': 'Databases & Persistence',
    'DdlUtils': 'Databases & Persistence', 'OpenJPA': 'Databases & Persistence',
    'Empire-DB': 'Databases & Persistence', 'Cayenne': 'Databases & Persistence',
    'OpenJPA Eclipse Plugin': 'Databases & Persistence',
    'Jackrabbit Content Repository': 'Databases & Persistence', 'Jackrabbit Site': 'Databases & Persistence',
    'Jackrabbit JCR-RMI': 'Databases & Persistence', 'Jackrabbit JCR Servlets': 'Databases & Persistence',
    'Jackrabbit JCR Classloader': 'Databases & Persistence', 'Jackrabbit JCR Benchmark': 'Databases & Persistence',
    'Jackrabbit OCM': 'Databases & Persistence', 'Jackrabbit JCR Tests': 'Databases & Persistence',
    'Jackrabbit Oak': 'Databases & Persistence', 'Jackrabbit FileVault': 'Databases & Persistence',
    'CouchDB': 'Databases & Persistence', 'Mavibot': 'Databases & Persistence',
    'Geode': 'Databases & Persistence', 'Ratis': 'Databases & Persistence',
    'Ignite': 'Databases & Persistence',

    # Web Frameworks & UI
    'Tapestry': 'Web Frameworks & UI', 'Struts 1': 'Web Frameworks & UI',
    'Struts 2': 'Web Frameworks & UI', 'Struts Sandbox': 'Web Frameworks & UI',
    'Struts Shared Resources': 'Web Frameworks & UI', 'Tiles': 'Web Frameworks & UI',
    'Tiles Showcase': 'Web Frameworks & UI', 'Tiles Shared Resources': 'Web Frameworks & UI',
    'Tiles Sandbox': 'Web Frameworks & UI', 'Tiles Request': 'Web Frameworks & UI',
    'Tiles Autotag': 'Web Frameworks & UI', 'Tiles Eval': 'Web Frameworks & UI',
    'Wicket': 'Web Frameworks & UI', 'MyFaces Core': 'Web Frameworks & UI',
    'MyFaces Tomahawk': 'Web Frameworks & UI', 'MyFaces Tobago': 'Web Frameworks & UI',
    'MyFaces Trinidad': 'Web Frameworks & UI', 'MyFaces Orchestra': 'Web Frameworks & UI',
    'MyFaces Commons': 'Web Frameworks & UI', 'MyFaces Extensions Validator': 'Web Frameworks & UI',
    'MyFaces Portlet Bridge': 'Web Frameworks & UI', 'MyFaces Extensions Scripting': 'Web Frameworks & UI',
    'MyFaces Test': 'Web Frameworks & UI', 'MyFaces CODI': 'Web Frameworks & UI',
    'Shale': 'Web Frameworks & UI', 'Pluto': 'Web Frameworks & UI', 'Portals': 'Web Frameworks & UI',
    'Portals Bridges (Retired)': 'Web Frameworks & UI', 'Portals Apps (Retired)': 'Web Frameworks & UI',
    'Beehive': 'Web Frameworks & UI', 'Cocoon (Retired)': 'Web Frameworks & UI',
    'Forrest (Retired)': 'Web Frameworks & UI', 'Velocity': 'Web Frameworks & UI',
    'Velocity Tools': 'Web Frameworks & UI', 'Velocity Sandbox': 'Web Frameworks & UI',
    'Pivot': 'Web Frameworks & UI', 'JSPWiki': 'Web Frameworks & UI',
    'Apache Roller': 'Web Frameworks & UI', 'Wookie': 'Web Frameworks & UI',
    'Openmeetings': 'Web Frameworks & UI', 'Apache Cordova': 'Web Frameworks & UI',
    'Apache Flex': 'Web Frameworks & UI', 'Apache Ripple': 'Web Frameworks & UI',
    'Shindig': 'Web Frameworks & UI', 'Guacamole': 'Web Frameworks & UI',
    'Weex (Retired)': 'Web Frameworks & UI', 'Superset': 'Web Frameworks & UI',
    'Apache ECharts': 'Web Frameworks & UI', 'NetBeans': 'Web Frameworks & UI',
    'OpenOffice': 'Web Frameworks & UI',

    # Web Services & Messaging
    'SOAP': 'Web Services & Messaging', 'Axis': 'Web Services & Messaging',
    'Axis-C++': 'Web Services & Messaging', 'Axis-WSIF': 'Web Services & Messaging',
    'XML-RPC': 'Web Services & Messaging', 'JaxMe': 'Web Services & Messaging',
    'WSRF': 'Web Services & Messaging', 'Muse': 'Web Services & Messaging',
    'Addressing': 'Web Services & Messaging', 'Kandula': 'Web Services & Messaging',
    'Sandesha': 'Web Services & Messaging', 'WSS4J': 'Web Services & Messaging',
    'Woden': 'Web Services & Messaging', 'Synapse': 'Web Services & Messaging',
    'Tuscany': 'Web Services & Messaging', 'WS-Commons': 'Web Services & Messaging',
    'ODE': 'Web Services & Messaging', 'ODE Web Console': 'Web Services & Messaging',
    'ODE JaCOb': 'Web Services & Messaging', 'Yoko - CORBA Server': 'Web Services & Messaging',
    'Abdera': 'Web Services & Messaging', 'CXF': 'Web Services & Messaging',
    'Qpid': 'Web Services & Messaging', 'Qpid Proton': 'Web Services & Messaging',
    'Qpid Dispatch': 'Web Services & Messaging', 'Qpid JMS': 'Web Services & Messaging',
    'ActiveMQ .Net': 'Web Services & Messaging', 'Stomp Specification': 'Web Services & Messaging',
    'ActiveRealTime (Retired)': 'Web Services & Messaging', 'ServiceMix': 'Web Services & Messaging',
    'ServiceMix Components': 'Web Services & Messaging', 'ActiveMQ C++ Client': 'Web Services & Messaging',
    'ActiveMQ Classic': 'Web Services & Messaging', 'Camel': 'Web Services & Messaging',
    'ActiveCluster': 'Web Services & Messaging', 'ActiveMQ Apollo (Retired)': 'Web Services & Messaging',
    'ActiveMQ Artemis': 'Web Services & Messaging', 'ActiveMQ OpenWire': 'Web Services & Messaging',
    'ActiveMQ CLI Tools': 'Web Services & Messaging', 'Apache RocketMQ': 'Web Services & Messaging',
    'Apache Dubbo': 'Web Services & Messaging', 'Apache ServiceComb': 'Web Services & Messaging',
    'Thrift': 'Web Services & Messaging', 'Etch': 'Web Services & Messaging',
    'MINA': 'Web Services & Messaging', 'MINA SSHD': 'Web Services & Messaging',
    'Axiom': 'Web Services & Messaging', 'XmlSchema': 'Web Services & Messaging',
    'Neethi': 'Web Services & Messaging', 'Rampart': 'Web Services & Messaging',
    'Rampart/C': 'Web Services & Messaging', 'Savan': 'Web Services & Messaging',
    'Santuario': 'Web Services & Messaging', 'VYSPER': 'Web Services & Messaging',
    'Wink': 'Web Services & Messaging', 'Traffic Server': 'Web Services & Messaging',
    'HttpComponents HttpCore': 'Web Services & Messaging', 'HttpComponents HttpClient': 'Web Services & Messaging',
    'HttpComponents HttpAsyncClient': 'Web Services & Messaging', 'Kitty': 'Web Services & Messaging',
    'Stratos': 'Web Services & Messaging', 'Olingo': 'Web Services & Messaging',
    'Axis2 Transports': 'Web Services & Messaging', 'Celix': 'Web Services & Messaging',
    'Apache EventMesh': 'Web Services & Messaging', 'APISIX': 'Web Services & Messaging',
    'ActiveMQ Website': 'Web Services & Messaging', 'Qpid Interoperability Test Suite': 'Web Services & Messaging',

    # Build, Release, & Project Management
    'Maven': 'Build, Release, & Project Management', 'Maven POMs (Moved to GitHub issues) ': 'Build, Release, & Project Management',
    'Maven ACR Plugin': 'Build, Release, & Project Management', 'Maven Ant Plugin (RETIRED)': 'Build, Release, & Project Management',
    'Maven Ant Tasks (RETIRED)': 'Build, Release, & Project Management', 'Maven Antrun Plugin': 'Build, Release, & Project Management',
    'Maven Archetype (Moved to GitHub Issues)': 'Build, Release, & Project Management',
    'Maven Archetype Bundles': 'Build, Release, & Project Management', 'Maven Assembly Plugin': 'Build, Release, & Project Management',
    'Maven Changelog Plugin': 'Build, Release, & Project Management', 'Maven Changes Plugin': 'Build, Release, & Project Management',
    'Maven Checkstyle Plugin': 'Build, Release, & Project Management', 'Maven Compiler Plugin (Moved to GitHub)': 'Build, Release, & Project Management',
    'Maven DOAP Plugin': 'Build, Release, & Project Management', 'Maven Dependency Plugin': 'Build, Release, & Project Management',
    'Maven Deploy Plugin (Moved to GitHub)': 'Build, Release, & Project Management',
    'Maven Documentation Checker Plugin (RETIRED) (Retired)': 'Build, Release, & Project Management',
    'Maven Doxia': 'Build, Release, & Project Management', 'Maven Doxia Sitetools': 'Build, Release, & Project Management',
    'Maven Doxia Tools': 'Build, Release, & Project Management', 'Maven EJB Plugin': 'Build, Release, & Project Management',
    'Maven EAR Plugin': 'Build, Release, & Project Management', 'Maven Eclipse Plugin (RETIRED)': 'Build, Release, & Project Management',
    'Maven Enforcer Plugin': 'Build, Release, & Project Management', 'Maven GPG Plugin': 'Build, Release, & Project Management',
    'Maven Help Plugin': 'Build, Release, & Project Management', 'Maven Indexer': 'Build, Release, & Project Management',
    'Maven Install Plugin (Moved to GitHub)': 'Build, Release, & Project Management', 'Maven Invoker Plugin': 'Build, Release, & Project Management',
    'Maven JAR Plugin': 'Build, Release, & Project Management', 'Maven JXR': 'Build, Release, & Project Management',
    'Maven Jar Signer Plugin': 'Build, Release, & Project Management', 'Maven Javadoc Plugin': 'Build, Release, & Project Management',
    'Maven Linkcheck Plugin': 'Build, Release, & Project Management', 'Maven PDF Plugin': 'Build, Release, & Project Management',
    'Maven PMD Plugin': 'Build, Release, & Project Management', 'Maven Patch Plugin (RETIRED)': 'Build, Release, & Project Management',
    'Maven Plugin Testing (Moved to GitHub Issues)': 'Build, Release, & Project Management',
    'Maven Plugin Tools': 'Build, Release, & Project Management',
    'Maven Project Info Reports Plugin (Moved to GitHub)': 'Build, Release, & Project Management',
    'Maven Project Web Site (Moved to GitHub Issues)': 'Build, Release, & Project Management',
    'Maven RAR Plugin': 'Build, Release, & Project Management', 'Maven Release Plugin': 'Build, Release, & Project Management',
    'Maven Remote Resources Plugin': 'Build, Release, & Project Management',
    'Maven Repository Plugin (RETIRED)': 'Build, Release, & Project Management', 'Maven Resources Plugin': 'Build, Release, & Project Management',
    'Maven SCM': 'Build, Release, & Project Management', 'Maven SCM Publish Plugin': 'Build, Release, & Project Management',
    'Maven Shade Plugin': 'Build, Release, & Project Management', 'Maven Shared Components': 'Build, Release, & Project Management',
    'Maven Site Plugin': 'Build, Release, & Project Management', 'Maven Source Plugin': 'Build, Release, & Project Management',
    'Maven Stage Plugin': 'Build, Release, & Project Management', 'Maven Skins': 'Build, Release, & Project Management',
    'Maven Surefire': 'Build, Release, & Project Management', 'Maven Toolchains Plugin': 'Build, Release, & Project Management',
    'Maven Verifier Plugin': 'Build, Release, & Project Management', 'Maven WAR Plugin': 'Build, Release, & Project Management',
    'Maven Wagon': 'Build, Release, & Project Management', 'Maven JDeps Plugin': 'Build, Release, & Project Management',
    'Maven JLink Plugin (Moved to GitHub)': 'Build, Release, & Project Management',
    'Maven JMod Plugin': 'Build, Release, & Project Management', 'Maven JDeprScan Plugin': 'Build, Release, & Project Management',
    'Maven Scripting': 'Build, Release, & Project Management', 'Maven Wrapper': 'Build, Release, & Project Management',
    'Maven Artifact Plugin': 'Build, Release, & Project Management', 'Maven Build Cache Extension': 'Build, Release, & Project Management',
    'Continuum': 'Build, Release, & Project Management', 'Gump': 'Build, Release, & Project Management',
    'GBuild': 'Build, Release, & Project Management', 'EasyAnt': 'Build, Release, & Project Management',
    'Ivy': 'Build, Release, & Project Management', 'IvyDE (Retired)': 'Build, Release, & Project Management',
    'Buildr (Retired)': 'Build, Release, & Project Management', 'Apache Rat': 'Build, Release, & Project Management',
    'Yetus': 'Build, Release, & Project Management', 'Archiva (Retired)': 'Build, Release, & Project Management',
    'Whimsy': 'Build, Release, & Project Management',

    # Libraries & Utilities (Commons & Core)
    'Apache Commons All': 'Libraries & Utilities (Commons & Core)', 'Commons Attributes': 'Libraries & Utilities (Commons & Core)',
    'Commons BeanUtils': 'Libraries & Utilities (Commons & Core)', 'Commons Betwixt': 'Libraries & Utilities (Commons & Core)',
    'Commons Chain': 'Libraries & Utilities (Commons & Core)', 'Commons CLI': 'Libraries & Utilities (Commons & Core)',
    'Commons Codec': 'Libraries & Utilities (Commons & Core)', 'Commons Collections': 'Libraries & Utilities (Commons & Core)',
    'Commons Configuration': 'Libraries & Utilities (Commons & Core)', 'Commons Daemon': 'Libraries & Utilities (Commons & Core)',
    'Commons DBCP': 'Libraries & Utilities (Commons & Core)', 'Commons DbUtils': 'Libraries & Utilities (Commons & Core)',
    'Commons Digester': 'Libraries & Utilities (Commons & Core)', 'Commons Discovery': 'Libraries & Utilities (Commons & Core)',
    'Commons EL': 'Libraries & Utilities (Commons & Core)', 'Commons Email': 'Libraries & Utilities (Commons & Core)',
    'Commons FeedParser': 'Libraries & Utilities (Commons & Core)', 'Commons FileUpload': 'Libraries & Utilities (Commons & Core)',
    'Commons IO': 'Libraries & Utilities (Commons & Core)', 'Commons JEXL': 'Libraries & Utilities (Commons & Core)',
    'Commons JXPath': 'Libraries & Utilities (Commons & Core)', 'Commons Lang': 'Libraries & Utilities (Commons & Core)',
    'Commons Launcher': 'Libraries & Utilities (Commons & Core)', 'Commons Logging': 'Libraries & Utilities (Commons & Core)',
    'Commons Math': 'Libraries & Utilities (Commons & Core)', 'Commons Modeler': 'Libraries & Utilities (Commons & Core)',
    'Commons Net': 'Libraries & Utilities (Commons & Core)', 'Commons Pool': 'Libraries & Utilities (Commons & Core)',
    'Commons Primitives': 'Libraries & Utilities (Commons & Core)', 'Commons Resources': 'Libraries & Utilities (Commons & Core)',
    'Commons Sandbox': 'Libraries & Utilities (Commons & Core)', 'Commons SCXML': 'Libraries & Utilities (Commons & Core)',
    'Commons Transaction': 'Libraries & Utilities (Commons & Core)', 'Commons Validator': 'Libraries & Utilities (Commons & Core)',
    'Commons VFS': 'Libraries & Utilities (Commons & Core)', 'Commons Jelly': 'Libraries & Utilities (Commons & Core)',
    'Commons Exec': 'Libraries & Utilities (Commons & Core)', 'Commons Compress': 'Libraries & Utilities (Commons & Core)',
    'Commons JCS': 'Libraries & Utilities (Commons & Core)', 'Commons Dormant': 'Libraries & Utilities (Commons & Core)',
    'Commons BSF': 'Libraries & Utilities (Commons & Core)', 'Commons JCI': 'Libraries & Utilities (Commons & Core)',
    'Commons Proxy': 'Libraries & Utilities (Commons & Core)', 'Commons Functor (Dormant)': 'Libraries & Utilities (Commons & Core)',
    'Commons OGNL (Dormant)': 'Libraries & Utilities (Commons & Core)', 'Commons CSV': 'Libraries & Utilities (Commons & Core)',
    'Commons Imaging': 'Libraries & Utilities (Commons & Core)', 'Commons BCEL': 'Libraries & Utilities (Commons & Core)',
    'Commons Text': 'Libraries & Utilities (Commons & Core)', 'Commons Crypto': 'Libraries & Utilities (Commons & Core)',
    'Commons Numbers': 'Libraries & Utilities (Commons & Core)', 'Commons RNG': 'Libraries & Utilities (Commons & Core)',
    'Commons Statistics': 'Libraries & Utilities (Commons & Core)', 'Commons Geometry': 'Libraries & Utilities (Commons & Core)',
    'Apache Commons Testing': 'Libraries & Utilities (Commons & Core)', 'Apache Commons RDF': 'Libraries & Utilities (Commons & Core)',
    'Commons Weaver': 'Libraries & Utilities (Commons & Core)',
    'Xerces-C++': 'Libraries & Utilities (Commons & Core)', 'Xerces2-J': 'Libraries & Utilities (Commons & Core)',
    'Xerces-P': 'Libraries & Utilities (Commons & Core)', 'XalanC': 'Libraries & Utilities (Commons & Core)',
    'XalanJ2': 'Libraries & Utilities (Commons & Core)', 'XMLBeans': 'Libraries & Utilities (Commons & Core)',
    'XML Commons': 'Libraries & Utilities (Commons & Core)', 'Log4cxx': 'Libraries & Utilities (Commons & Core)',
    'C++ Standard Library': 'Libraries & Utilities (Commons & Core)', 'MINA': 'Libraries & Utilities (Commons & Core)',
    'XBean': 'Libraries & Utilities (Commons & Core)', 'Triplesec': 'Libraries & Utilities (Commons & Core)',
    'TripleSoup': 'Libraries & Utilities (Commons & Core)', 'UIMA': 'Libraries & Utilities (Commons & Core)',
    'PDFBox': 'Libraries & Utilities (Commons & Core)', 'Tika': 'Libraries & Utilities (Commons & Core)',
    'Groovy': 'Libraries & Utilities (Commons & Core)', 'Juneau': 'Libraries & Utilities (Commons & Core)',
    'OpenNLP': 'Libraries & Utilities (Commons & Core)', 'Apache Jena': 'Libraries & Utilities (Commons & Core)',
    'Daffodil': 'Libraries & Utilities (Commons & Core)', 'Flagon': 'Libraries & Utilities (Commons & Core)',
    'AriaTosca': 'Libraries & Utilities (Commons & Core)', 'Maven Resolver': 'Libraries & Utilities (Commons & Core)',
    'Commons Jelly': 'Libraries & Utilities (Commons & Core)', 'ECS': 'Libraries & Utilities (Commons & Core)',
    'Agila': 'Libraries & Utilities (Commons & Core)', 'DdlUtils': 'Libraries & Utilities (Commons & Core)',
    'Turbine': 'Libraries & Utilities (Commons & Core)', 'HiveMind': 'Libraries & Utilities (Commons & Core)',
    'XWork': 'Libraries & Utilities (Commons & Core)',

    # Servers & Runtimes
    'Geronimo': 'Servers & Runtimes', 'Geronimo-Devtools': 'Servers & Runtimes',
    'TomEE': 'Servers & Runtimes', 'James Server': 'Servers & Runtimes',
    'James jSieve': 'Servers & Runtimes', 'James jSPF': 'Servers & Runtimes',
    'James Postage': 'Servers & Runtimes', 'James Mailbox': 'Servers & Runtimes',
    'James Imap': 'Servers & Runtimes', 'James MPT': 'Servers & Runtimes',
    'James Hupa': 'Servers & Runtimes', 'James jDKIM': 'Servers & Runtimes',
    'James Protocols': 'Servers & Runtimes', 'FtpServer': 'Servers & Runtimes',
    'Karaf': 'Servers & Runtimes', 'Felix': 'Servers & Runtimes',
    'TomEE Arquillian Test Porting Initiative': 'Servers & Runtimes',
    'Meecrowave': 'Servers & Runtimes', 'VYSPER': 'Servers & Runtimes',

    # Cloud & Virtualization
    'CloudStack': 'Cloud & Virtualization', 'jclouds': 'Cloud & Virtualization',
    'DeltaCloud': 'Cloud & Virtualization', 'Provisionr': 'Cloud & Virtualization',
    'Apache Whirr (retired)': 'Cloud & Virtualization', 'Brooklyn': 'Cloud & Virtualization',
    'Stratos': 'Cloud & Virtualization', 'Apache OpenAZ': 'Cloud & Virtualization',
    'Libcloud': 'Cloud & Virtualization', 'Nuvem': 'Cloud & Virtualization',
    'Tashi': 'Cloud & Virtualization', 'VCL': 'Cloud & Virtualization',

    # Security & Identity
    'Shiro': 'Security & Identity', 'Directory': 'Security & Identity',
    'Directory Naming': 'Security & Identity', 'Directory ApacheDS': 'Security & Identity',
    'Directory Studio': 'Security & Identity', 'Directory Shared (Please use DIRAPI instead)': 'Security & Identity',
    'Directory Groovy LDAP': 'Security & Identity', 'Directory Kerberos': 'Security & Identity',
    'Directory Client API': 'Security & Identity', 'WSS4J': 'Security & Identity',
    'FORTRESS': 'Security & Identity', 'Apache Oltu': 'Security & Identity',
    'Ranger': 'Security & Identity', 'CXF-Fediz': 'Security & Identity',
    'Apache SCIMple': 'Security & Identity', 'Apache OpenAZ': 'Security & Identity',

    # Incubator & Retired/Dormant Projects (or those without a clear modern domain)
    'Incubator': 'Incubator & Retired/Dormant Projects', 'Attic': 'Incubator & Retired/Dormant Projects',
    'jUDDI (Retired)': 'Incubator & Retired/Dormant Projects', 'Scout (Retired)': 'Incubator & Retired/Dormant Projects',
    'Pubscribe': 'Incubator & Retired/Dormant Projects', 'Mirae': 'Incubator & Retired/Dormant Projects',
    'Portals Bridges (Retired)': 'Incubator & Retired/Dormant Projects', 'TSIK': 'Incubator & Retired/Dormant Projects',
    'Forrest (Retired)': 'Incubator & Retired/Dormant Projects', 'Cocoon (Retired)': 'Incubator & Retired/Dormant Projects',
    'Buildr (Retired)': 'Incubator & Retired/Dormant Projects', 'Labs WebArch draft-fielding-http (Retired)': 'Incubator & Retired/Dormant Projects',
    'Imperius': 'Incubator & Retired/Dormant Projects', 'Asyncweb': 'Incubator & Retired/Dormant Projects',
    'OpenEJB Eclipse Plugin': 'Incubator & Retired/Dormant Projects', 'Olio': 'Incubator & Retired/Dormant Projects',
    'Droids': 'Incubator & Retired/Dormant Projects', 'Enterprise Social Messaging Environment (ESME)': 'Incubator & Retired/Dormant Projects',
    'Portals Apps (Retired)': 'Incubator & Retired/Dormant Projects', 'Chukwa (retired)': 'Incubator & Retired/Dormant Projects',
    'Bluesky': 'Incubator & Retired/Dormant Projects', 'Chemistry (Retired)': 'Incubator & Retired/Dormant Projects',
    'Open Relevance Project ': 'Incubator & Retired/Dormant Projects', 'VXQuery (Retired)': 'Incubator & Retired/Dormant Projects',
    'HISE': 'Incubator & Retired/Dormant Projects', 'Clerezza (Retired)': 'Incubator & Retired/Dormant Projects',
    'CXF Distributed OSGi (Retired)': 'Incubator & Retired/Dormant Projects', 'OODT (Retired)': 'Incubator & Retired/Dormant Projects',
    'Apache Whirr (retired)': 'Incubator & Retired/Dormant Projects', 'Kalumet (Retired)': 'Incubator & Retired/Dormant Projects',
    'Commons Functor (Dormant)': 'Incubator & Retired/Dormant Projects', 'Apache AWF': 'Incubator & Retired/Dormant Projects',
    'Crunch (Retired)': 'Incubator & Retired/Dormant Projects', 'Streams (Retired) (Retired)': 'Incubator & Retired/Dormant Projects',
    'Marmotta (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache Open Climate Workbench (Retired)': 'Incubator & Retired/Dormant Projects',
    'Apache MetaModel (Retired)': 'Incubator & Retired/Dormant Projects', 'Sentry (Retired)': 'Incubator & Retired/Dormant Projects',
    'Usergrid (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache Twill (Retired)': 'Incubator & Retired/Dormant Projects',
    'Steve': 'Incubator & Retired/Dormant Projects', 'REEF (Retired)': 'Incubator & Retired/Dormant Projects',
    'Apache Lens (Retired)': 'Incubator & Retired/Dormant Projects', 'Corinthia': 'Incubator & Retired/Dormant Projects',
    'Archiva (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache Trafodion (Retired)': 'Incubator & Retired/Dormant Projects',
    'Apache HAWQ (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache Concerted': 'Incubator & Retired/Dormant Projects',
    'Eagle (Retired)': 'Incubator & Retired/Dormant Projects', 'Metron (Retired)': 'Incubator & Retired/Dormant Projects',
    'Milagro (Retired)': 'Incubator & Retired/Dormant Projects', 'Joshua (Retired)': 'Incubator & Retired/Dormant Projects',
    'Bahir (Retired)': 'Incubator & Retired/Dormant Projects', 'PredictionIO (Retired)': 'Incubator & Retired/Dormant Projects',
    'Spot (Retired)': 'Incubator & Retired/Dormant Projects', 'Weex (Retired)': 'Incubator & Retired/Dormant Projects',
    'Pulsar (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache MXNet (Retired)': 'Incubator & Retired/Dormant Projects',
    'Apache DataLab (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache Marvin (Retired)': 'Incubator & Retired/Dormant Projects',
    'Tuweni (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache Liminal (Retired)': 'Incubator & Retired/Dormant Projects',
    'Apache AGE (old)': 'Incubator & Retired/Dormant Projects', 'Apache BlueMarlin (Retired)': 'Incubator & Retired/Dormant Projects',
    'Apache Hop (Retired)': 'Incubator & Retired/Dormant Projects', 'Apache Celeborn': 'Incubator & Retired/Dormant Projects',
    'Test Project': 'Incubator & Retired/Dormant Projects', 'Muse': 'Incubator & Retired/Dormant Projects',
    'ews': 'Incubator & Retired/Dormant Projects', 'mod_python': 'Incubator & Retired/Dormant Projects',
    'Graffito': 'Incubator & Retired/Dormant Projects', 'WADI': 'Incubator & Retired/Dormant Projects',
    'DayTrader': 'Incubator & Retired/Dormant Projects', 'Heraldry': 'Incubator & Retired/Dormant Projects',
    'Lokahi': 'Incubator & Retired/Dormant Projects', 'River (Retired)': 'Incubator & Retired/Dormant Projects',
    'Anakia': 'Incubator & Retired/Dormant Projects', 'Texen': 'Incubator & Retired/Dormant Projects',
    'Dvsl': 'Incubator & Retired/Dormant Projects', 'Click Eclipse': 'Incubator & Retired/Dormant Projects',
    'Click': 'Incubator & Retired/Dormant Projects', 'ACE': 'Incubator & Retired/Dormant Projects',
    'PhotArk': 'Incubator & Retired/Dormant Projects', 'Kato': 'Incubator & Retired/Dormant Projects',
    'Causeway': 'Incubator & Retired/Dormant Projects', 'ALOIS': 'Incubator & Retired/Dormant Projects',
    'NPanday': 'Incubator & Retired/Dormant Projects', 'Stanbol (Retired)': 'Incubator & Retired/Dormant Projects',
    'Wave': 'Incubator & Retired/Dormant Projects', 'Mesos': 'Incubator & Retired/Dormant Projects',
    'Airavata': 'Incubator & Retired/Dormant Projects', 'Apache DirectMemory': 'Incubator & Retired/Dormant Projects',
    'Podling Suitable Names Search': 'Incubator & Retired/Dormant Projects', 'Apache Whisker': 'Incubator & Retired/Dormant Projects',
    'Apache Tentacles': 'Incubator & Retired/Dormant Projects', 'cTAKES': 'Incubator & Retired/Dormant Projects',
    'Apache Blur': 'Incubator & Retired/Dormant Projects', 'Apache Helix': 'Incubator & Retired/Dormant Projects',
    'Apache Onami': 'Incubator & Retired/Dormant Projects', 'Hadoop Development Tools': 'Incubator & Retired/Dormant Projects',
    'Apache Coral': 'Incubator & Retired/Dormant Projects',
    'TomEE Arquillian Test Porting Initiative': 'Incubator & Retired/Dormant Projects',
    'Phoenix Tephra': 'Incubator & Retired/Dormant Projects', 'Phoenix Omid': 'Incubator & Retired/Dormant Projects',
    'Gossip': 'Incubator & Retired/Dormant Projects', 'Hivemall': 'Incubator & Retired/Dormant Projects',
    'Apache Lucy-Clownfish': 'Incubator & Retired/Dormant Projects', 'HTrace': 'Incubator & Retired/Dormant Projects',
    'Tamaya': 'Incubator & Retired/Dormant Projects', 'Apache Wayang': 'Incubator & Retired/Dormant Projects',
    'AMATERASU': 'Incubator & Retired/Dormant Projects',

    # Content Management & XML
    'Sling': 'Content Management & XML', 'Lucy': 'Content Management & XML',
    'XAP': 'Content Management & XML', 'OFBiz': 'Content Management & XML',
    'DocBook Framework': 'Content Management & XML',

    # IoT & Edge Computing
    'Apache IoTDB': 'IoT & Edge Computing', 'Apache NuttX': 'IoT & Edge Computing',
    'Apache NiFi MiNiFi - MOVED TO NIFI PROJECT': 'IoT & Edge Computing',
    'Apache NiFi MiNiFi C++': 'IoT & Edge Computing', 'NiFi Standard Libraries': 'IoT & Edge Computing',
    'Apache NiFi': 'IoT & Edge Computing',

    # Community & Administrative
    'Legal Discuss': 'Community & Administrative', 'Public Relations': 'Community & Administrative',
    'Community Development': 'Community & Administrative', 'Trademarks Committee': 'Community & Administrative',
    'Diversity and Inclusion': 'Community & Administrative', 'Central Services': 'Community & Administrative',
    'Comdev GSOC': 'Community & Administrative', 'Podling Suitable Names Search': 'Community & Administrative',
    'www.apache.org website': 'Community & Administrative',

    # Programming Languages & Runtimes
    'Harmony': 'Programming Languages & Runtimes', 'Groovy': 'Programming Languages & Runtimes',
    'C++ Standard Library': 'Programming Languages & Runtimes', 'OpenWebBeans': 'Programming Languages & Runtimes',
    'Johnzon': 'Programming Languages & Runtimes', 'Zeta Components': 'Programming Languages & Runtimes',
    'AltRMI': 'Programming Languages & Runtimes', 'Avalon': 'Programming Languages & Runtimes',
    'Avalon Phoenix': 'Programming Languages & Runtimes', 'Avalon Metro Central': 'Programming Languages & Runtimes',
    'Excalibur Components': 'Programming Languages & Runtimes', 'Excalibur Fortress': 'Programming Languages & Runtimes',
    'PMC (Project Management Committee)': 'Programming Languages & Runtimes', # Assuming this is a project, or a category
    'Apache Nemo': 'Programming Languages & Runtimes', 'Apache Chainsaw': 'Programming Languages & Runtimes',
    'Apache Ozone': 'Programming Languages & Runtimes',

    # Graphics & Imaging
    'Batik': 'Graphics & Imaging', 'FOP': 'Graphics & Imaging',
    'XMLGraphicsCommons': 'Graphics & Imaging', 'PDFBox': 'Graphics & Imaging',

    # Geospatial
    'Apache Sedona': 'Geospatial', 'Spatial Information Systems': 'Geospatial',

    # Other / Uncategorized / Cross-Domain
    'Test Project': 'Other / Uncategorized / Cross-Domain', # Explicitly placed here
    'Apache DirectMemory': 'Other / Uncategorized / Cross-Domain',
    'Apache Coral': 'Other / Uncategorized / Cross-Domain',
    'Apache Zipkin': 'Other / Uncategorized / Cross-Domain',
    'Apache Training': 'Other / Uncategorized / Cross-Domain',
    'Apache Pegasus': 'Other / Uncategorized / Cross-Domain',
    'Apache Traffic Control': 'Other / Uncategorized / Cross-Domain',
    'Apache Pulsar (Retired)': 'Other / Uncategorized / Cross-Domain',
    'NiFi Registry - MOVED TO NIFI PROJECT': 'Other / Uncategorized / Cross-Domain',
    'Apache Gobblin': 'Other / Uncategorized / Cross-Domain',
    'IMPALA': 'Other / Uncategorized / Cross-Domain',
}
