# Display name for the features in the dataset.
# 'project_id', 'project_key', 'project_name', 'project_category',
#        'average_lifespan', 'average_workspan', 'average_change_density',
#        'average_reassignment_rate', 'average_description_edit_rate',
#        'average_author_churn', 'average_fix_version_change_rate',
#        'average_time_estimate_change_rate', 'average_resolution_change_rate',
#        'average_status_change_rate', 'average_priority_change_rate',
#        'average_issue_type_change_rate', 'total_changes', 'total_assignees',
#        'total_reporters', 'total_members', 'total_issues',
#        'assignee_reporter_ratio', 'num_status_to_do_pct',
#        'num_status_in_progress_pct', 'num_status_done_pct',
#        'num_status_other_pct', 'incomplete_ratio', 'num_resolution_fixed_pct',
#        'num_resolution_duplicate_pct', 'num_resolution_won't_fix_pct',
#        'num_resolution_invalid_pct', 'num_resolution_incomplete_pct',
#        'num_resolution_other_pct', 'resolution_ratio', 'reopen_ratio',
#        'num_issue_type_bug_ratio', 'num_issue_type_feature_ratio',
#        'num_issue_type_improvement_ratio', 'num_issue_type_task_ratio',
#        'num_issue_type_other_ratio', 'bug_to_development_ratio',
#        'num_priority_high_ratio', 'num_priority_medium_ratio',
#        'num_priority_low_ratio', 'num_priority_other_ratio',
#        'high_priority_bug_ratio', 'schedule_risk', 'quality_risk',
#        'combined_risk', 'risk_category'

FEATURE_NAMES = {
    'project_id': 'Project ID',
    'project_key': 'Project Key',
    'project_name': 'Project Name',
    'project_category': 'Project Category',
    'average_lifespan': 'Average Resolution Time (days)',
    'average_workspan': 'Average Work Time (days)',
    'average_change_density': 'Average Change Density (per day)',
    'average_reassignment_rate': 'Average Reassignment Rate',
    'average_description_edit_rate': 'Average Description Edit Rate',
    'average_author_churn': 'Average Author Churn (authors per change)',
    'average_fix_version_change_rate': 'Average Fix Version Change Rate',
    'average_time_estimate_change_rate': 'Average Time Estimate Change Rate',
    'average_resolution_change_rate': 'Average Resolution Change Rate',
    'average_status_change_rate': 'Average Status Change Rate',
    'average_priority_change_rate': 'Average Priority Change Rate',
    'average_issue_type_change_rate': 'Average Issue Type Change Rate',
    'total_changes': 'Total Changes',
    'total_assignees': 'Total Assignees',
    'total_reporters': 'Total Reporters',
    'total_members': 'Total Members',
    'total_issues': 'Total Issues',
    'assignee_reporter_ratio': 'Assignee to Reporter Ratio',
    'num_status_to_do_pct': 'To Do Issues (%)',
    'num_status_in_progress_pct': 'In Progress Issues (%)',
    'num_status_done_pct': 'Done Issues (%)',
    'num_status_other_pct': 'Other Status Issues (%)',
    'incomplete_ratio': 'Incomplete Issues Ratio',
    'num_resolution_fixed_pct': 'Fixed Issues (%)',
    'num_resolution_duplicate_pct': 'Duplicate Issues (%)',
    'num_resolution_won\'t_fix_pct': 'Won\'t Fix Issues (%)',
    'num_resolution_invalid_pct': 'Invalid Issues (%)',
    'num_resolution_incomplete_pct': 'Incomplete Issues (%)',
    'num_resolution_other_pct': 'Other Resolution Issues (%)',
    'resolution_ratio': 'Resolution Ratio',
    'reopen_ratio': 'Reopened Issues Ratio',
    'num_issue_type_bug_ratio': 'Bug Issues Ratio',
    'num_issue_type_feature_ratio': 'Feature Issues Ratio',
    'num_issue_type_improvement_ratio': 'Improvement Issues Ratio',
    'num_issue_type_task_ratio': 'Task Issues Ratio',
    'num_issue_type_other_ratio': 'Other Issues Ratio',
    'bug_to_development_ratio': 'Bug to Development Issues Ratio',
    'num_priority_high_ratio': 'High Priority Issues Ratio',
    'num_priority_medium_ratio': 'Medium Priority Issues Ratio',
    'num_priority_low_ratio': 'Low Priority Issues Ratio',
    'num_priority_other_ratio': 'Other Priority Issues Ratio',
    'high_priority_bug_ratio': 'High Priority Bug Issues Ratio',
    'schedule_risk': 'Schedule Risk',
    'quality_risk': 'Quality Risk',
    'combined_risk': 'Combined Risk',
    'risk_category': 'Risk Category'
}